### ISSUE TITLE
"When will the source code be released?"

### ISSUE THREAD

**Issue by lyshuang** [qizekun/ShapeLLM#1]
I've been thoroughly impressed by your work on "ShapeLLM: Universal 3D Object Understanding for Embodied Interaction" and am keen to explore it further. Could you please let me know when the associated source code might be available? "Thank you very much, and I apologize for any disturbance."

**Comment by qizekun** [comment]
Thank you for your attention! The code will be released today.

**Comment by RunpeiDong** [comment]
Hi @lyshuang,

The code has been released. Enjoy.
