### ISSUE TITLE
Help with running the demo

### ISSUE THREAD

**Issue by akcaesar7029** [qizekun/ShapeLLM#14]
After having cloned the repository and installing the requirements, I ran this command 'python -m llava.serve.cli \
    --model-path qizekun/ShapeLLM_13B_general_v1.0 \
    --pts-file assets/instrument.npy' as shown in the repo.

 However, I ran into problems. 
`  File "/home/akshay7029/anaconda3/envs/shapellm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!`

Can anyone please give me some advice on how to do this correctly. Or, if someone has managed to run the demo, please let me know the steps.

**Comment by qizekun** [comment]
Hello,
This issue arises due to insufficient GPU memory. You can resolve it by adding the --load-8bit or --load-4bit option to the command.
