### ISSUE TITLE
How can we train even smaller model

### ISSUE THREAD

**Issue by utilpotatocat** [qizekun/ShapeLLM#3]
the 7B base mdoel is sometimes even too large 
how can we train mini mdoel like 1B or even 6M mini-model
Which configurations in the project should be modified in this way?

**Comment by qizekun** [comment]
Hi,

I'm sorry for the late reply.
The current phenomenon is that only large language models possess strong capabilities in text comprehension, and employing smaller language models may significantly impair performance in tasks such as VQA. 
Nevertheless, you could consider experimenting with Google's Gemma model, which has a minimal parameter count of only 2 billion and has demonstrated capabilities surpassing those of LLaMA-7B.
