### ISSUE TITLE
How long to train the RECON++ model?

### ISSUE THREAD

**Issue by hanhung** [qizekun/ShapeLLM#5]
Hello,

Thanks for releasing the code for this. I was wonder how long it takes to train the RECON++ (HyBrid/Ensembled) part of the model (without the ShapeLLM).

Thanks.

**Comment by qizekun** [comment]
Hi, 

The HyBrid/Ensembled part and weights will be released soon, the training time in 8×A800 is about one day.

**Comment by hanhung** [comment]
Thanks!
