### ISSUE TITLE
Zero-shot Understanding with point clouds only

### ISSUE THREAD

**Issue by Yjonben** [qizekun/ShapeLLM#6]
If my point cloud data only has three channels of xyz, how can I perform Zero-shot Understanding? And my vision_tower always inexplicably becomes six channels of xyz+rgb.
![image](https://github.com/qizekun/ShapeLLM/assets/44564089/8ea865e5-bd50-4b0f-8422-ce8263a9b282)

**Comment by qizekun** [comment]
Hello, you can simulate a blank object in the point cloud file by adding three values of 0.6, representing the color white, as follows: [x, y, z, 0.6, 0.6, 0.6].

**Comment by Yjonben** [comment]
That works, but the results might not be as good. I'm wondering if there's a way to achieve zero-shot understanding using just XYZ. Sincere thanks, can I add your WeChat for further communication?

**Comment by qizekun** [comment]
Ok, my WeChat is 15176182051.
