### ISSUE TITLE
Potential error in Openshape data loading

### ISSUE THREAD

**Issue by akshay-loci** [qizekun/ShapeLLM#9]
Hi! Going through the codebase I found this line in the dataloader for objaverse assets:

https://github.com/qizekun/ShapeLLM/blob/f0273b80c5861ec9d8fc8418d3a020b653dd95bb/ReConV2/datasets/OpenShape.py#L96

This line is executed regardless of the number of image queries being used for training - if we want to use say 13 image queries this results in choosing one embedding and duplicating it 13 times. This results in the bipartite matching + multi-view distillation loss not really doing what it is supposed to.

Would be great if you could take a look.

**Comment by qizekun** [comment]
Hi,
Thank you very much for pointing this out. We inadvertently made an error while organizing and cleaning the code.

**Comment by qizekun** [comment]
We have fixed this bug. Please check the latest commits.
